### ISSUE TITLE
[rc3]time stamp is zero for grubdb and sbat variables

### ISSUE THREAD

**Issue by nasastry** [open-power/secvarctl#81]
```
READING sbat :
        Timestamp: 0000-00-00 00:00:00 UTC
ESL 1:
        ESL SIG LIST SIZE: 51
        GUID is : 50ab5d6046e00043abb63dd810dd8b23
        Signature type is: SBAT
        Data: sbat,1


        Found 1 ESL's

RESULT: SUCCESS
```

```
READING grubdb :
        Timestamp: 0000-00-00 00:00:00 UTC
ESL 1:
        ESL SIG LIST SIZE: 1083
        GUID is : a159c0a5e494a74a87b5ab155c2bf072
        Signature type is: X509
        Certificate-1:  Found certificate info
...
```

**Comment by nick-child-ibm** [comment]
Hi Nageswara, thanks for testing!
Can you provide the commands that led to this? Did you generate these files or were these tested on an actual guest SB environment?
I am trying to reproduce with `secvarctl verify` but it IS returning with an updated timestamp:
```
$ echo "sbat,1
grub,1                 
gub.ibm.grub,1" > sbat_in

$ ./bin/secvarctl-dbg -m guest generate f:a -n sbat -o sbat.auth -i sbat_in -k test/guest/testenv/PK/PK.key -c test/guest/testenv/PK/PK.crt
RESULT: SUCCESS

$ ./bin/secvarctl-dbg -m guest verify -p test/guest/testenv/ -u sbat sbat.auth -v
<skipping to end of output>
	Timestamp: 2024-01-03 15:47:17 UTC
ESL 1:
	ESL SIG LIST SIZE: 73
	GUID is : 50ab5d6046e00043abb63dd810dd8b23
	Signature type is: SBAT
	Data: sbat,1
grub,1
gub.ibm.grub,1


	Found 1 ESL's

RESULT: SUCCESS
```
This claims that the new timestamp would be `2024-01-03 15:47:17 UTC` if the operation was successful.
Can you provide some more information on the origins of the `grubdb` and `sbat` data which you are reading?

**Comment by nasastry** [comment]
Some how missed the above message. As per Sudhakar Kuppusamy, This is the way it behaves. Better he adds comment here before we close this.

**Comment by nasastry** [comment]
> This claims that the new timestamp would be `2024-01-03 15:47:17 UTC` if the operation was successful. Can you provide some more information on the origins of the `grubdb` and `sbat` data which you are reading?

I was trying to read the data written to PKS and noticed zero time stamp.

**Comment by nasastry** [comment]
The distribution provided auth variables has time stamp as zero. which is expected checked on both RHEL and SLES. This issue is not a bug. Closing.
