### ISSUE TITLE
Make check: Test fail after generating keys using guest_generate_testdata.py.

### ISSUE THREAD

**Issue by Krishan-Saraswat** [open-power/secvarctl#89]
`make[1]: Entering directory '/home/secvarctl/test'
100+0 records in
100+0 records out
100 bytes copied, 0.000321773 s, 311 kB/s
4+0 records in
4+0 records out
64 bytes copied, 0.000117305 s, 546 kB/s
......
----------------------------------------------------------------------
Ran 6 tests in 5.389s

OK
........
----------------------------------------------------------------------
Ran 8 tests in 16.116s

OK
..........
----------------------------------------------------------------------
Ran 10 tests in 6.315s

OK
make[1]: Leaving directory '/home/secvarctl/test'
***************
[root@ test]# python3 guest_generate_testdata.py
***************
[root@ secvarctl]# make check
make[1]: Entering directory '/home/secvarctl/test'
100+0 records in
100+0 records out
100 bytes copied, 0.000171369 s, 584 kB/s
4+0 records in
4+0 records out
64 bytes copied, 6.3943e-05 s, 1.0 MB/s
......
----------------------------------------------------------------------
Ran 6 tests in 2.846s

OK
........
----------------------------------------------------------------------
Ran 8 tests in 15.092s

OK
......FF..
======================================================================
FAIL: test_verify (__main__.Test.test_verify)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/secvarctl/test/guest_tests.py", line 330, in test_verify
    self.assertCmdTrue(cmd)
  File "/home/secvarctl/test/common.py", line 51, in assertCmdTrue
    self.assertCmd(args, True)
  File "/home/secvarctl/test/common.py", line 48, in assertCmd
    tmp_assert(bool(result), msg=f"{msg}\n{result}")
AssertionError: False is not true : Expected success, but failed: '/home/secvarctl/bin/secvarctl-dbg -m guest verify -u KEK ./testdata/guest/authfiles/KEK_by_PK.auth -p ./testenv/guest/'
stdout:
RESULT: FAILURE

stderr:
Could not verify PKCS#7 signature against trusted key
Failed to apply variable update.

======================================================================
FAIL: test_verify_reset_auth (__main__.Test.test_verify_reset_auth)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/secvarctl/test/guest_tests.py", line 425, in test_verify_reset_auth
    self.assertCmdTrue(cmd)
  File "/home/secvarctl/test/common.py", line 51, in assertCmdTrue
    self.assertCmd(args, True)
  File "/home/secvarctl/test/common.py", line 48, in assertCmd
    tmp_assert(bool(result), msg=f"{msg}\n{result}")
AssertionError: False is not true : Expected success, but failed: '/home/secvarctl/bin/secvarctl-dbg -m guest verify -u KEK ./testdata/guest/authfiles/reset_KEK_by_PK.auth -p ./testenv/guest/'
stdout:
WARNING: appended ESL is empty, (valid key reset file)...
RESULT: FAILURE

stderr:
Could not verify PKCS#7 signature against trusted key
Failed to apply variable update.

----------------------------------------------------------------------
Ran 10 tests in 3.149s

FAILED (failures=2)
make[1]: *** [Makefile:33: check-guest] Error 1
make[1]: Leaving directory '/home/secvarctl/test'
make: *** [Makefile:154: check] Error 2

**Comment by erichte-ibm** [comment]
Fixed by #90, and released in `v1.1.0`
